version: "3"   #Vers√£o do Docker compose
services:           #docker pull node
    nodejs-container:
        build: 
            context: .
            dockerfile: ./ifood/Dockerfile
        links:
            - mongodb-container
        ports:
            - "3000:3000"
        depends_on:
            - mongodb-container
        restart: on-failure
    mongodb-container: #Docker pull Mongo
        build: 
            context: .
            dockerfile: dockerfile-mongodb.dockerfile
        volumes: 
            - mongodb-data:/Users/felipeassaf/Documents/git/FIAP_FASE06/Fase6/Docker/data
volumes: 
    mongodb-data: {}   